### ISSUE TITLE
Source is actually Kaggle?

### ISSUE THREAD

**Issue by matthew-brett** [jennybc/lotr#2]
Thanks very much for posting this dataset.

For me, the link to the IBM site doesn't work any more, maybe I don't have the right permissions.

But - it looks like your data may be the same as the data here: https://www.kaggle.com/mokosan/lord-of-the-rings-character-data#WordsByCharacter.csv

Is it possible that is the actual source?  I mean, that's where IBM got it from?

**Comment by jennybc** [comment]
Well, I created the data here from the (now defunct) IBM manyeyes site over 6 years ago, whereas the Kaggle version first appeared  2017-11-27 and is attributed to scraping the Lord of the Rings wiki:

https://www.kaggle.com/mokosan/lord-of-the-rings-character-data/

https://www.kaggle.com/mokosan/lord-of-the-rings-character-data/metadata

It's probably more likely that the wiki ingested the same data as I originally found and that eventually got scraped into kaggle.

**Comment by matthew-brett** [comment]
Hmm - yes - now I look at it, I can't see where the Kaggle author is getting the `WordsByCharacter.csv` data, in their code at https://github.com/MokoSan/FSharpAdvent.  And it's *very* similar to the IBM data, with the same column headings and order, and the same format for the chapter titles.   I put up an issue to ask the author about the data.

**Comment by matthew-brett** [comment]
He just answered : issue 1 in https://github.com/MokoSan/FSharpAdvent - the data didn't come from the Wiki...

**Comment by jennybc** [comment]
In general, I find that sites like Kaggle have some pretty terrible (lack of) data attribution.
